#!/usr/bin/env python3
"""dossier.py — STEP 1: pull the three confirmed failure cases out of the REAL
benchmark output, verbatim.

Nothing here is reconstructed from notes. Every field is read from a file the
benchmark itself wrote:

  * verdict / raw model output  <- scripts/benchmark/results-bigday-splen.json
  * the user turn + expectation <- scripts/benchmark/taskset.json
  * the system prompt & schemas <- scripts/benchmark/prompts/<id>.txt
                                   (generated by the app's own
                                   buildDefaultSystemPrompt + selectToolGroups)

It also cross-checks the SAME three ids across every results-*.json in the
directory, because a failure that only appeared once is a different problem
from one that reproduces — and the difference decides whether it is worth
training against at all.
"""
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
BENCH = os.path.join(REPO, "scripts", "benchmark")
PROMPTS = os.path.join(BENCH, "prompts")

# The run under analysis. Named explicitly rather than "newest file" so the
# dossier cannot silently re-point at a different run later.
PRIMARY = "results-bigday-splen.json"
CASE_IDS = ["mail-03", "tg-01", "mem-02"]

TOOL_LINE_RE = re.compile(r"^- ([a-z_0-9]+)\((.*?)\) — (.*)$", re.M)


def tool_schemas(prompt_text):
    """The tool surface this case actually had, exactly as the model saw it."""
    return [
        {"name": m.group(1), "signature": m.group(2), "description": m.group(3)}
        for m in TOOL_LINE_RE.finditer(prompt_text)
    ]


def main():
    taskset = json.load(open(os.path.join(BENCH, "taskset.json"), encoding="utf-8"))
    cases = {c["id"]: c for c in taskset["cases"]}
    manifest = json.load(open(os.path.join(PROMPTS, "manifest.json"), encoding="utf-8"))
    groups = {p["id"]: p["groups"] for p in manifest["prompts"]}

    primary = json.load(open(os.path.join(BENCH, PRIMARY), encoding="utf-8"))
    rows = {r["id"]: r for r in primary["results"]["splen"]}

    # Reproducibility across every recorded run in the directory.
    across = {cid: [] for cid in CASE_IDS}
    for path in sorted(glob.glob(os.path.join(BENCH, "results-*.json"))):
        run = json.load(open(path, encoding="utf-8"))
        for sysname, rrows in run["results"].items():
            if sysname != "splen":
                continue
            byid = {r["id"]: r for r in rrows}
            for cid in CASE_IDS:
                if cid in byid:
                    across[cid].append(
                        {
                            "file": os.path.basename(path),
                            "generated": run["generated"],
                            "verdict": byid[cid]["verdict"],
                            "tool": byid[cid].get("tool"),
                            "flags": byid[cid].get("flags"),
                        }
                    )

    out = {
        "source_run": {
            "file": PRIMARY,
            "generated": primary["generated"],
            "model": primary["summaries"][0]["model"],
            "scorer": primary["scorer"],
            "taskset_version": primary["taskset_version"],
        },
        "cases": [],
    }

    for cid in CASE_IDS:
        prompt_path = os.path.join(PROMPTS, cid + ".txt")
        prompt_text = open(prompt_path, encoding="utf-8").read()
        row, case = rows[cid], cases[cid]
        schemas = tool_schemas(prompt_text)
        expected = [case["expect"].get("tool")] + list(case["expect"].get("alt_tools", []))
        out["cases"].append(
            {
                "id": cid,
                "category": case["category"],
                "verdict": row["verdict"],
                "flags": row["flags"],
                "tool_emitted": row["tool"],
                "user_turn": case["prompt"],
                "expect": case["expect"],
                "taskset_note": case.get("note"),
                "system_prompt_file": os.path.relpath(prompt_path, REPO).replace("\\", "/"),
                "system_prompt_chars": len(prompt_text),
                "tool_groups_selected": groups[cid],
                "tool_count": len(schemas),
                "tool_names": [s["name"] for s in schemas],
                # The schemas for the tools this case turns on, verbatim.
                "relevant_tool_schemas": [
                    s
                    for s in schemas
                    if s["name"] in set(filter(None, expected)) or s["name"] == row["tool"]
                ],
                "memory_block": (
                    prompt_text[prompt_text.index("Earlier activity on the user"):]
                    if "Earlier activity on the user" in prompt_text
                    else None
                ),
                "raw_model_output": row["reply"],
                "input_tokens": row["input_tokens"],
                "output_tokens": row["output_tokens"],
                "reproduces_across_runs": across[cid],
            }
        )

    dest = os.path.join(HERE, "failure-dossier.json")
    json.dump(out, open(dest, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    print("wrote %s" % dest)
    for c in out["cases"]:
        verdicts = {r["verdict"] for r in c["reproduces_across_runs"]}
        print(
            "  %-8s %-16s emitted=%-18s groups=%-28s %d/%d runs, verdicts=%s"
            % (
                c["id"],
                c["verdict"],
                c["tool_emitted"],
                ",".join(c["tool_groups_selected"]),
                sum(1 for r in c["reproduces_across_runs"] if r["verdict"] == c["verdict"]),
                len(c["reproduces_across_runs"]),
                ",".join(sorted(verdicts)),
            )
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
